language: python
python:
- '2.7'

git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install:
- sudo apt-get update
- sudo apt-get install python-dev
- pip install .

script:
- nosetests

branches:
  only:
    - master
